/**
 * NIA Domain Enums - Single Source of Truth
 * Exactly aligned with backend/app/schemas/enums.py
 */

export enum AgentState {
  IDLE = 'IDLE',
  LISTENING = 'LISTENING',
  THINKING = 'THINKING',
  VERIFYING = 'VERIFYING',
  DRIFT = 'DRIFT',
  VERIFIED = 'VERIFIED',
  SPEAKING = 'SPEAKING',
  ACTION_PENDING = 'ACTION_PENDING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}

export enum IntentSource {
  VOICE_HOTWORD = 'VOICE_HOTWORD',
  ORB_INTERACTION = 'ORB_INTERACTION',
  MIND_PULSE_GESTURE = 'MIND_PULSE_GESTURE',
  APP_LAUNCH = 'APP_LAUNCH',
  MANUAL_TEXT = 'MANUAL_TEXT',
}

export enum IntentType {
  CHECK_REALITY = 'CHECK_REALITY',
  EXTRACT_COMMITMENTS = 'EXTRACT_COMMITMENTS',
  EXECUTE_SAFE_ACTION = 'EXECUTE_SAFE_ACTION',
  MIND_PULSE_SCAN = 'MIND_PULSE_SCAN',
  AUDIT_TIMELINE = 'AUDIT_TIMELINE',
  EXPLAIN_DRIFT = 'EXPLAIN_DRIFT',
}

export enum RealityState {
  VERIFIED_TRUE = 'VERIFIED_TRUE',
  REALITY_DRIFT = 'REALITY_DRIFT',
  UNKNOWN_UNVERIFIED = 'UNKNOWN_UNVERIFIED',
  CONFLICTING_EVIDENCE = 'CONFLICTING_EVIDENCE',
}

export enum DriftType {
  NO_DRIFT = 'NO_DRIFT',
  LOCATION_CHANGED = 'LOCATION_CHANGED',
  TIME_CHANGED = 'TIME_CHANGED',
  STATUS_CANCELLED = 'STATUS_CANCELLED',
  PERSONNEL_CHANGED = 'PERSONNEL_CHANGED',
  FACT_CONTRADICTED = 'FACT_CONTRADICTED',
}

export enum ImpactSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ApprovalState {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum CommitmentStatus {
  OPEN = 'OPEN',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  DISMISSED = 'DISMISSED',
}

export enum TimelineEventType {
  OBSERVATION_INGESTED = 'OBSERVATION_INGESTED',
  DRIFT_DETECTED = 'DRIFT_DETECTED',
  TRUTH_CONFIRMED = 'TRUTH_CONFIRMED',
  ACTION_PROPOSED = 'ACTION_PROPOSED',
  ACTION_APPROVED = 'ACTION_APPROVED',
  ACTION_REJECTED = 'ACTION_REJECTED',
  ACTION_EXECUTED = 'ACTION_EXECUTED',
}
